/* BMS application. This file is NOT generated by STM32CubeMX. */
#include "bms_app.h"
#include "bms_telemetry.h"
#include "bms_lcd.h"
#include "bms_buttons.h"
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/* Peripheral handles are defined in CubeMX-generated main.c. */
extern ADC_HandleTypeDef hadc1;
extern I2C_HandleTypeDef hi2c1;
extern TIM_HandleTypeDef htim2;
extern UART_HandleTypeDef huart2;

/* Original voltage calibration and LiFePO4 pack OCV table. */
static const float ADC_REFERENCE_V = 3.3f;
static const float DIV_RATIO[4] = {1.0f, 2.0f, 3.0606f, 4.03030303f};
static const float CALIBRATION[4] = {1.0f, 1.0f, 1.0f, 1.004876f};
/* Extra per-TAP calibration; set ONLY from independent DMM measurements.
 * These corrections apply to cumulative voltages B1-, B2-, B3-, B4+.
 * CALIBRATION[] and DIV_RATIO[] remain as in the existing firmware. */
static const float ADS_TAP_GAIN[4] = {1.0f, 1.0f, 1.0f, 1.0f};
static const float ADS_TAP_OFFSET_V[4] = {0.0f, 0.0f, 0.0f, 0.0f};
static const float EMA_ALPHA = 0.2f;
static const float BATTERY_CAPACITY_AH = 15.0f;
/* ACS712 signal acquisition & calibration.
 * Keep the original Vadc correction (+0.1215 V). The separate -0.968 A
 * adjustment is the requested MANUAL zero-current calibration, not an
 * automatically discovered offset. Set it only using a verified 0 A test.
 *
 * ACS712_SENSITIVITY_V_PER_A = 0.100 applies to the nominal 20 A variant;
 * confirm your module's actual variant and direction before using the value
 * for SOC. Never assume load MOSFET OFF means battery current is zero.
 *
 * ACS712 is read using STM32 ADC1_IN6. Invalid readings remain INVALID:
 * do not replace them with a previously filtered sample. */
#define ACS712_NUM_SAMPLES                  32u
#define ACS712_TRIM_EACH_END                 3u
#define ACS712_SAMPLE_SPACING_MS             1u
#define ACS712_FILTER_ALPHA                 0.25f
#define ACS712_FILTER_FAST_ALPHA            0.65f
#define ACS712_FILTER_FAST_STEP_A           0.30f

static const float ACS712_GAIN = 1.0000f;
static const float ACS712_ADC_OFFSET_V = 0.1215f;
static const float ACS712_VZERO_V = 2.50f;
static const float ACS712_SENSITIVITY_V_PER_A = 0.100f;
static const float ACS712_CURRENT_OFFSET_A = 0.924f;

#if ACS712_NUM_SAMPLES <= (2u * ACS712_TRIM_EACH_END)
#error "ACS712 needs samples remaining after trimming."
#endif
#define SENSOR_INTERVAL_MS    250u
#define SOC_INIT_AFTER_MS   10000u
#define ADC_TIMEOUT_MS         5u
#define I2C_TIMEOUT_MS        15u

/* LM75 family: temperature register is signed and left-justified.
 * Verify your actual chip marking before choosing resolution:
 *  9 bits: standard LM75, 0.5 C/LSB (7 low unused bits)
 * 11 bits: e.g. NXP LM75A, 0.125 C/LSB (5 low unused bits).
 * Default 11 also reads a standard 9-bit LM75 correctly when unused
 * low bits are zero, as required by the standard LM75 register format.
 * Select 9 if your specific 9-bit clone has unspecified low bits.
 * A low-pass filter cannot create more physical sensor accuracy/resolution.
 * One independent read per sensorUpdate (~250 ms). Avoid multiple reads
 * within a single sensor conversion; those would be copies of one sample.
 * Use 0 offset / unit gain until calibrated against a reference thermometer. */
#define LM75_ADDR_HAL                  (0x48u << 1)
#define LM75_TEMP_REGISTER            0x00u
#define LM75_CONFIG_REGISTER          0x01u
#define LM75_RESOLUTION_BITS          11u /* Preserves LM75A 0.125 C resolution */
#define LM75_TEMP_GAIN                 1.0f
#define LM75_TEMP_OFFSET_C             0.0f
#define LM75_I2C_RETRIES               2u /* Maximum attempts, no unbounded wait */
#define LM75_RETRY_DELAY_MS            2u
#define LM75_HISTORY_STALE_MS       1000u
#define LM75_FILTER_ALPHA              0.25f
#define LM75_FILTER_FAST_ALPHA         0.70f
#define LM75_FILTER_FAST_STEP_C        2.0f

#if (LM75_RESOLUTION_BITS != 9u) && (LM75_RESOLUTION_BITS != 11u)
#error "Select LM75_RESOLUTION_BITS 9 or 11 after confirming the IC variant"
#endif

/* ADS1115: single-ended AIN0..AIN3, 128 SPS, PGA +/-4.096 V.
 * IMPORTANT: Set VDD to the MEASURED ADS1115 supply voltage (mV).
 * PGA full-scale is NOT permission to drive a pin above VDD.
 * This software rail check cannot protect hardware against overvoltage.
 * Hardware must keep ALL AIN pins inside [GND, VDD] under ALL conditions. */
#define ADS1115_ADDR_HAL             (0x4Au << 1)
#define ADS1115_VDD_MV                3300u /* CHANGE TO MEASURED VDD */
#define ADS1115_RAIL_MARGIN_MV          20u
#define ADS1115_CONV_TIMEOUT_MS        18u
#define ADS1115_READS_PER_TAP           3u
#define ADS1115_REPEAT_SPREAD_MV       35u /* at AIN, not battery tap */
#define ADS1115_CONFIG_BASE       0x8383u

#if (ADS1115_VDD_MV <= ADS1115_RAIL_MARGIN_MV)
#error "ADS1115_VDD_MV must exceed ADS1115_RAIL_MARGIN_MV"
#endif

#define PACK_OVERVOLT_V    14.55f /* retained from original project */
#define PACK_UNDERVOLT_V    9.30f /* retained from original project */
#define PACK_OCV_TABLE_SIZE 19u

/* Button handling lives in bms_buttons.c/.h. PB5 is button 1; the remaining
 * three slots are reserved and disabled until the real GPIOs are assigned. */

/* Load output + on-board status LED.
 * PA7 = external load/MOSFET control, active HIGH.
 * PC13 = on-board LED on common STM32F103C8T6 Blue Pill boards, active LOW.
 * Keeping both in one helper guarantees the LED always follows the load state. */
#define BMS_LOAD_GPIO_PORT          GPIOA
#define BMS_LOAD_PIN                GPIO_PIN_7
#define BMS_LED_GPIO_PORT           GPIOC
#define BMS_LED_PIN                 GPIO_PIN_13
#define BMS_LED_ON_STATE            GPIO_PIN_RESET
#define BMS_LED_OFF_STATE           GPIO_PIN_SET

static const float OCV_TABLE[PACK_OCV_TABLE_SIZE] = {
    14.64f,14.59f,13.60f,13.30f,13.21f,13.17f,13.14f,13.10f,13.02f,
    12.90f,12.80f,12.63f,12.43f,11.78f,11.35f,11.11f,10.79f,10.50f,10.00f
};
static const float SOC_TABLE[PACK_OCV_TABLE_SIZE] = {
    100.0f,98.0f,95.0f,90.0f,80.0f,70.0f,60.0f,50.0f,40.0f,30.0f,
    20.0f,15.0f,10.0f,5.0f,4.0f,3.0f,2.0f,1.0f,0.0f
};

volatile uint8_t mosfetState = 0u;
volatile bool g_protectionLatched = false;
volatile bool g_measurementValid = false;
float Cell1 = 0.0f, Cell2 = 0.0f, Cell3 = 0.0f, Cell4 = 0.0f;
float Cell_Tong = 0.0f, SOC = 0.0f;
static float s_currentA = 0.0f;
static bool s_haveCurrentFilter = false;
static bool s_haveFilter = false;
static float s_filteredTapV[4] = {0.0f, 0.0f, 0.0f, 0.0f};

/* LM75 filter uses readings from different ~250 ms acquisition cycles. */
static float s_lm75HistoryC[3] = {0.0f, 0.0f, 0.0f};
static uint8_t s_lm75HistoryCount = 0u;
static uint8_t s_lm75HistoryIndex = 0u;
static float s_lm75FilteredC = 0.0f;
static bool s_lm75HasFilter = false;

/* Live Expressions: ERROR=0 OK, 1=temp read, 2=config read,
 * 3=shutdown, 4=out of physical range. RawC is UNFILTERED; only the
 * smoothed value is published to LCD/UART. No thermal protection uses
 * the filtered value (existing BMS has no dedicated thermal cutoff). */
volatile float g_bmsLm75RawC = 0.0f;
volatile float g_bmsLm75MedianC = 0.0f;
volatile float g_bmsLm75FilteredC = 0.0f;
volatile uint16_t g_bmsLm75RawWord = 0u;
volatile uint8_t g_bmsLm75ErrorStage = 0u;
volatile uint8_t g_bmsLm75HistoryCount = 0u;
volatile uint32_t g_bmsLm75ReadOkCount = 0u;
volatile uint32_t g_bmsLm75ReadErrorCount = 0u;
volatile uint32_t g_bmsLm75LastGoodTick_ms = 0u;
volatile uint32_t g_bmsLm75FilterResetCount = 0u;

/* ADS1115 diagnostics in CubeIDE Live Expressions.
 * g_bmsAdsErrorStage: 0=OK, 1=config write, 2=config poll/read,
 * 3=conversion timeout, 4=conversion register, 5=raw/rail,
 * 6=unstable samples, 7=voltage/tap plausibility. */
volatile uint8_t  g_bmsAdsErrorStage = 0u;
volatile uint8_t  g_bmsAdsErrorChannel = 0xFFu;
volatile uint32_t g_bmsAdsReadErrorCount = 0u;
volatile uint32_t g_bmsAdsValidWindowCount = 0u;
volatile int16_t  g_bmsAdsRawMedian[4] = {0, 0, 0, 0};
volatile uint16_t g_bmsAdsSpreadInput_mV[4] = {0u, 0u, 0u, 0u};
volatile float    g_bmsAdsTapRawV[4] = {0.0f, 0.0f, 0.0f, 0.0f};
volatile float    g_bmsAdsCellRawV[4] = {0.0f, 0.0f, 0.0f, 0.0f};

/* ACS712 diagnostics: observe these in STM32CubeIDE Live Expressions. */
volatile uint16_t g_bmsAcsTrimmedAdcRaw = 0u;
volatile uint16_t g_bmsAcsRawMin = 0u;
volatile uint16_t g_bmsAcsRawMax = 0u;
volatile float g_bmsAcsInstantA = 0.0f;
volatile float g_bmsAcsFilteredA = 0.0f;
volatile uint32_t g_bmsAcsReadErrorCount = 0u;
static bool s_socInitialized = false;
static uint32_t s_lastCoulombMs = 0u;
static BMS_Telemetry_t s_latest = {0};

/* Button diagnostics / debounce state (visible in Live Expressions). */
volatile uint32_t g_buttonPressCnt = 0u;
volatile uint32_t g_buttonRejectedCnt = 0u;
volatile GPIO_PinState g_buttonStableState = GPIO_PIN_SET;


static float clampFloat(float x, float lo, float hi)
{
    return (x < lo) ? lo : ((x > hi) ? hi : x);
}

static uint16_t milliUnsigned(float x)
{
    x = clampFloat(x * 1000.0f, 0.0f, 65535.0f);
    return (uint16_t)(x + 0.5f);
}

static int16_t milliSigned(float x)
{
    x = clampFloat(x * 1000.0f, -32768.0f, 32767.0f);
    return (int16_t)(x >= 0.0f ? x + 0.5f : x - 0.5f);
}

static float getPackSocFromVoltage(float packV)
{
    if (packV >= OCV_TABLE[0]) return SOC_TABLE[0];
    if (packV <= OCV_TABLE[PACK_OCV_TABLE_SIZE-1u])
        return SOC_TABLE[PACK_OCV_TABLE_SIZE-1u];
    for (uint8_t i = 0u; i < PACK_OCV_TABLE_SIZE - 1u; ++i) {
        if (packV <= OCV_TABLE[i] && packV >= OCV_TABLE[i+1u]) {
            const float a = (packV - OCV_TABLE[i+1u]) /
                            (OCV_TABLE[i] - OCV_TABLE[i+1u]);
            return SOC_TABLE[i+1u] + a * (SOC_TABLE[i] - SOC_TABLE[i+1u]);
        }
    }
    return 0.0f;
}

static bool adcRead(uint32_t channel, uint32_t *raw)
{
    ADC_ChannelConfTypeDef cfg = {0};
    cfg.Channel = channel;
    cfg.Rank = ADC_REGULAR_RANK_1;
    cfg.SamplingTime = ADC_SAMPLETIME_239CYCLES_5;
    if (HAL_ADC_ConfigChannel(&hadc1, &cfg) != HAL_OK) return false;
    if (HAL_ADC_Start(&hadc1) != HAL_OK) return false;
    if (HAL_ADC_PollForConversion(&hadc1, ADC_TIMEOUT_MS) != HAL_OK) {
        (void)HAL_ADC_Stop(&hadc1);
        return false;
    }
    *raw = HAL_ADC_GetValue(&hadc1);
    (void)HAL_ADC_Stop(&hadc1);
    return true;
}

/* One acquisition window:
 * 1) collect 32 ADC samples, spaced 1 ms apart to cover part of the
 *    low-frequency interference cycle (not only 32 adjacent conversions);
 * 2) discard 3 lowest and 3 highest readings to suppress isolated spikes;
 * 3) apply the original voltage calibration and the requested -0.968 A;
 * 4) apply an adaptive EMA to DISPLAY/TELEMETRY only;
 * 5) return the unlagged trimmed value separately for SOC integration.
 *
 * A digital filter reduces random noise, not ADC gain, Vref, temperature
 * drift, or an incorrectly calibrated ACS712 sensitivity. */
static bool readCurrentA(float *displayAmps, float *socAmps)
{
    if ((displayAmps == NULL) || (socAmps == NULL))
        return false;

    uint16_t values[ACS712_NUM_SAMPLES];

    for (uint8_t i = 0u; i < ACS712_NUM_SAMPLES; ++i) {
        uint32_t raw = 0u;
        if (!adcRead(ADC_CHANNEL_6, &raw) || (raw > 4095u)) {
            g_bmsAcsReadErrorCount++;
            return false;
        }

        values[i] = (uint16_t)raw;
        if ((i + 1u) < ACS712_NUM_SAMPLES)
            HAL_Delay(ACS712_SAMPLE_SPACING_MS);
    }

    /* Insertion sort: only 32 values, small fixed memory/CPU overhead. */
    for (uint8_t i = 1u; i < ACS712_NUM_SAMPLES; ++i) {
        const uint16_t key = values[i];
        uint8_t j = i;
        while ((j > 0u) && (values[j - 1u] > key)) {
            values[j] = values[j - 1u];
            --j;
        }
        values[j] = key;
    }

    g_bmsAcsRawMin = values[0u];
    g_bmsAcsRawMax = values[ACS712_NUM_SAMPLES - 1u];

    /* A clipped central distribution cannot be recovered by filtering. */
    if ((values[ACS712_TRIM_EACH_END] <= 1u) ||
        (values[ACS712_NUM_SAMPLES - ACS712_TRIM_EACH_END - 1u] >= 4094u)) {
        g_bmsAcsReadErrorCount++;
        return false;
    }

    uint32_t sum = 0u;
    for (uint8_t i = ACS712_TRIM_EACH_END;
         i < (ACS712_NUM_SAMPLES - ACS712_TRIM_EACH_END);
         ++i) {
        sum += values[i];
    }

    const float meanRaw = (float)sum /
        (float)(ACS712_NUM_SAMPLES - 2u * ACS712_TRIM_EACH_END);
    g_bmsAcsTrimmedAdcRaw = (uint16_t)(meanRaw + 0.5f);

    const float adcV = meanRaw * (ADC_REFERENCE_V / 4095.0f);
    const float correctedV = adcV * ACS712_GAIN + ACS712_ADC_OFFSET_V;
    const float instantA = ((correctedV - ACS712_VZERO_V) /
                            ACS712_SENSITIVITY_V_PER_A) -
                           ACS712_CURRENT_OFFSET_A;

    /* Preserve the existing broad plausibility check. Any bad sample is
     * invalid and must not drive LCD, SOC, or a new telemetry-valid flag. */
    if (!((instantA > -30.0f) && (instantA < 30.0f))) {
        g_bmsAcsReadErrorCount++;
        return false;
    }

    g_bmsAcsInstantA = instantA;

    if (!s_haveCurrentFilter) {
        s_currentA = instantA;
        s_haveCurrentFilter = true;
    } else {
        const float deltaA = instantA - s_currentA;
        const float absDeltaA = (deltaA < 0.0f) ? -deltaA : deltaA;
        const float alpha = (absDeltaA >= ACS712_FILTER_FAST_STEP_A)
            ? ACS712_FILTER_FAST_ALPHA
            : ACS712_FILTER_ALPHA;
        s_currentA += alpha * deltaA;
    }

    g_bmsAcsFilteredA = s_currentA;
    *displayAmps = s_currentA;
    *socAmps = instantA;
    return true;
}

/* ADS1115 acquisition: every single-shot is explicitly started and polled
 * to completion, then the matching channel conversion is read. A fixed delay
 * alone can accidentally return an old conversion after I2C/timing trouble.
 * Return false on ANY failure: stale data are never reused. */
static bool adsFail(uint8_t channel, uint8_t stage)
{
    g_bmsAdsErrorChannel = channel;
    g_bmsAdsErrorStage = stage;
    g_bmsAdsReadErrorCount++;
    return false;
}

static bool adsReadOneRaw(uint8_t channel, int16_t *raw)
{
    if ((channel > 3u) || (raw == NULL)) return adsFail(channel, 2u);

    const uint16_t config = (uint16_t)(ADS1115_CONFIG_BASE |
                                     ((uint16_t)(channel + 4u) << 12));
    uint8_t command[3] = {0x01u, (uint8_t)(config >> 8), (uint8_t)config};
    if (HAL_I2C_Master_Transmit(&hi2c1, ADS1115_ADDR_HAL, command, 3u,
                                I2C_TIMEOUT_MS) != HAL_OK)
        return adsFail(channel, 1u);

    const uint32_t begin = HAL_GetTick();
    bool complete = false;
    do {
        uint8_t cfg[2];
        if (HAL_I2C_Mem_Read(&hi2c1, ADS1115_ADDR_HAL, 0x01u,
                             I2C_MEMADD_SIZE_8BIT, cfg, 2u,
                             I2C_TIMEOUT_MS) != HAL_OK)
            return adsFail(channel, 2u);

        const uint16_t status = (uint16_t)(((uint16_t)cfg[0] << 8) | cfg[1]);
        /* Ensure that neither another driver nor an interrupted write has
         * silently changed the requested multiplexer or PGA setting. */
        if ((status & 0x7E00u) != (config & 0x7E00u))
            return adsFail(channel, 2u);
        if ((status & 0x8000u) != 0u) {
            complete = true;
            break;
        }
        HAL_Delay(1u);
    } while ((uint32_t)(HAL_GetTick() - begin) < ADS1115_CONV_TIMEOUT_MS);

    if (!complete) return adsFail(channel, 3u);

    uint8_t data[2];
    if (HAL_I2C_Mem_Read(&hi2c1, ADS1115_ADDR_HAL, 0x00u,
                         I2C_MEMADD_SIZE_8BIT, data, 2u,
                         I2C_TIMEOUT_MS) != HAL_OK)
        return adsFail(channel, 4u);

    *raw = (int16_t)(((uint16_t)data[0] << 8) | data[1]);

    /* For +/-4.096 V PGA each raw code = 0.125 mV. Since these are
     * single-ended readings, negative/near-FSR/near-VDD are invalid.
     * Rail checks detect SOME clipping, but cannot validate the input wiring. */
    if ((*raw < 0) || (*raw >= 32760) ||
        ((uint32_t)(*raw) >=
         ((uint32_t)(ADS1115_VDD_MV - ADS1115_RAIL_MARGIN_MV) * 8u)))
        return adsFail(channel, 5u);

    return true;
}

/* Three independent observations of EACH tap. Interleave the four channels
 * over three rounds to reduce intra-pack timing skew between taps.
 * Median rejects one impulsive outlier; a consistency check rejects data
 * without at least two reasonably agreeing readings. */
static bool adsReadPackTaps(float tapsV[4])
{
    int16_t raw[4][ADS1115_READS_PER_TAP];

    for (uint8_t round = 0u; round < ADS1115_READS_PER_TAP; ++round)
        for (uint8_t ch = 0u; ch < 4u; ++ch)
            if (!adsReadOneRaw(ch, &raw[ch][round])) return false;

    for (uint8_t ch = 0u; ch < 4u; ++ch) {
        int16_t low = raw[ch][0u];
        int16_t mid = raw[ch][1u];
        int16_t high = raw[ch][2u];
        if (low > mid) { int16_t tmp = low; low = mid; mid = tmp; }
        if (mid > high) { int16_t tmp = mid; mid = high; high = tmp; }
        if (low > mid) { int16_t tmp = low; low = mid; mid = tmp; }

        /* Difference in ADS codes * 0.125 mV/code. All three far apart
         * indicates a noisy/rapidly moving input; do NOT invent a value. */
        const uint16_t closeCodes = (uint16_t)(ADS1115_REPEAT_SPREAD_MV * 8u);
        if (((uint16_t)(mid - low) > closeCodes) &&
            ((uint16_t)(high - mid) > closeCodes))
            return adsFail(ch, 6u);

        const uint16_t bestPairSpread = ((mid - low) < (high - mid))
            ? (uint16_t)(mid - low) : (uint16_t)(high - mid);
        g_bmsAdsSpreadInput_mV[ch] = (uint16_t)((bestPairSpread + 4u) / 8u);
        g_bmsAdsRawMedian[ch] = mid;

        const float inputV = (float)mid * 0.000125f;
        tapsV[ch] = inputV * DIV_RATIO[ch] * CALIBRATION[ch] *
                    ADS_TAP_GAIN[ch] + ADS_TAP_OFFSET_V[ch];
        g_bmsAdsTapRawV[ch] = tapsV[ch];
    }

    g_bmsAdsErrorStage = 0u;
    g_bmsAdsErrorChannel = 0xFFu;
    return true;
}

/* Decode a signed, left-justified LM75 temperature register without
 * depending on implementation-defined right shifts of negative values.
 * Ignore unused LSBs according to the confirmed chip resolution. */
static float lm75DecodeC(uint16_t word)
{
    const uint16_t mask = (uint16_t)(0xFFFFu << (16u - LM75_RESOLUTION_BITS));
    const uint16_t valid = (uint16_t)(word & mask);
    const int32_t signedRaw = ((valid & 0x8000u) != 0u)
        ? ((int32_t)valid - 65536)
        : (int32_t)valid;
    return (float)signedRaw * (1.0f / 256.0f);
}

static float lm75Median3(float a, float b, float c)
{
    if (a > b) { const float t = a; a = b; b = t; }
    if (b > c) { const float t = b; b = c; c = t; }
    if (a > b) { const float t = a; a = b; b = t; }
    return b;
}

static void lm75ResetHistory(void)
{
    s_lm75HistoryCount = 0u;
    s_lm75HistoryIndex = 0u;
    s_lm75HasFilter = false;
    g_bmsLm75HistoryCount = 0u;
    g_bmsLm75FilterResetCount++;
}

static bool lm75Fail(uint8_t stage)
{
    g_bmsLm75ErrorStage = stage;
    g_bmsLm75ReadErrorCount++;
    /* Do not set TEMP_VALID and do not reuse the previous reading as new.
     * After an extended outage, clear the 3-sample median and EMA so that
     * old thermal values cannot contaminate the first recovered sample. */
    if (s_lm75HasFilter &&
        ((uint32_t)(HAL_GetTick() - g_bmsLm75LastGoodTick_ms) >=
         LM75_HISTORY_STALE_MS)) {
        lm75ResetHistory();
    }
    return false;
}

/* Returns one freshly acquired, filtered temperature for LCD/UART.
 * A limited I2C retry avoids a transient NACK on the bus shared with LCD
 * and ADS1115. Config register is read-only here: shutdown (bit 0) is
 * diagnosed, not silently cleared by firmware. */
static bool readPackTemperature(float *tempC)
{
    if (tempC == NULL) return lm75Fail(1u);

    uint8_t tempBuf[2] = {0u, 0u};
    uint8_t config = 0u;
    uint8_t errorStage = 1u;
    bool readOK = false;

    for (uint8_t attempt = 0u; attempt < LM75_I2C_RETRIES; ++attempt) {
        if (HAL_I2C_Mem_Read(&hi2c1, LM75_ADDR_HAL, LM75_TEMP_REGISTER,
                             I2C_MEMADD_SIZE_8BIT, tempBuf, 2u,
                             I2C_TIMEOUT_MS) != HAL_OK) {
            errorStage = 1u;
        } else if (HAL_I2C_Mem_Read(&hi2c1, LM75_ADDR_HAL,
                                    LM75_CONFIG_REGISTER,
                                    I2C_MEMADD_SIZE_8BIT, &config, 1u,
                                    I2C_TIMEOUT_MS) != HAL_OK) {
            errorStage = 2u;
        } else {
            readOK = true;
            break;
        }

        if ((attempt + 1u) < LM75_I2C_RETRIES)
            HAL_Delay(LM75_RETRY_DELAY_MS);
    }

    if (!readOK) return lm75Fail(errorStage);
    if ((config & 0x01u) != 0u) return lm75Fail(3u); /* Shutdown: stale register */

    const uint16_t word = (uint16_t)(((uint16_t)tempBuf[0] << 8) | tempBuf[1]);
    const float physicalC = lm75DecodeC(word);
    if (!((physicalC >= -55.0f) && (physicalC <= 125.0f)))
        return lm75Fail(4u);

    /* User-defined gain/offset are 1/0 until reference-calibrated. */
    const float measuredC = physicalC * LM75_TEMP_GAIN + LM75_TEMP_OFFSET_C;
    if (!((measuredC >= -55.0f) && (measuredC <= 125.0f)))
        return lm75Fail(4u);

    const uint32_t tick = HAL_GetTick();
    if (s_lm75HasFilter &&
        ((uint32_t)(tick - g_bmsLm75LastGoodTick_ms) >=
         LM75_HISTORY_STALE_MS)) {
        lm75ResetHistory();
    }

    g_bmsLm75RawWord = word;
    g_bmsLm75RawC = measuredC;
    g_bmsLm75LastGoodTick_ms = tick;
    g_bmsLm75ReadOkCount++;
    g_bmsLm75ErrorStage = 0u;

    s_lm75HistoryC[s_lm75HistoryIndex] = measuredC;
    s_lm75HistoryIndex = (uint8_t)((s_lm75HistoryIndex + 1u) % 3u);
    if (s_lm75HistoryCount < 3u) s_lm75HistoryCount++;
    g_bmsLm75HistoryCount = s_lm75HistoryCount;

    float medianC = measuredC;
    if (s_lm75HistoryCount == 2u)
        medianC = (s_lm75HistoryC[0] + s_lm75HistoryC[1]) * 0.5f;
    else if (s_lm75HistoryCount == 3u)
        medianC = lm75Median3(s_lm75HistoryC[0],
                               s_lm75HistoryC[1],
                               s_lm75HistoryC[2]);

    g_bmsLm75MedianC = medianC;
    if (!s_lm75HasFilter) {
        s_lm75FilteredC = medianC;
        s_lm75HasFilter = true;
    } else {
        const float delta = medianC - s_lm75FilteredC;
        const float absDelta = (delta < 0.0f) ? -delta : delta;
        const float alpha = (absDelta >= LM75_FILTER_FAST_STEP_C)
            ? LM75_FILTER_FAST_ALPHA : LM75_FILTER_ALPHA;
        s_lm75FilteredC += alpha * delta;
    }

    g_bmsLm75FilteredC = s_lm75FilteredC;
    *tempC = s_lm75FilteredC;
    return true;
}

/* Single source of truth for the physical load state.
 *
 * enable = true:
 *   PA7  = HIGH  -> load/MOSFET ON
 *   PC13 = LOW   -> on-board LED ON (Blue Pill active-low LED)
 *
 * enable = false:
 *   PA7  = LOW   -> load/MOSFET OFF
 *   PC13 = HIGH  -> on-board LED OFF
 */
static void setLoadOutput(bool enable)
{
    mosfetState = enable ? 1u : 0u;

    HAL_GPIO_WritePin(
        BMS_LOAD_GPIO_PORT,
        BMS_LOAD_PIN,
        enable ? GPIO_PIN_SET : GPIO_PIN_RESET);

    HAL_GPIO_WritePin(
        BMS_LED_GPIO_PORT,
        BMS_LED_PIN,
        enable ? BMS_LED_ON_STATE : BMS_LED_OFF_STATE);
}

static void latchProtectionFault(void)
{
    g_protectionLatched = true;
    setLoadOutput(false);
}

/* Apply the manual output request from the push button.
 * OFF is always accepted. ON is accepted only when the BMS can verify that
 * measurements are valid and no protection fault is latched. */
static void handleButtonPress(void)
{
    g_buttonPressCnt++;

    if (mosfetState != 0u) {
        setLoadOutput(false);
        return;
    }

    if (g_protectionLatched || !g_measurementValid) {
        g_buttonRejectedCnt++;
        return;
    }

    setLoadOutput(true);
}

static void sensorUpdate(uint32_t now)
{
    BMS_Telemetry_t sample = {0};
    float taps[4], cells[4], currentA = 0.0f, currentSocA = 0.0f, tempC = 0.0f;
    bool voltageOK = adsReadPackTaps(taps), currentOK, tempOK;
    currentOK = readCurrentA(&currentA, &currentSocA);
    tempOK = readPackTemperature(&tempC);
    if (voltageOK) {
        cells[0] = taps[0];
        cells[1] = taps[1] - taps[0];
        cells[2] = taps[2] - taps[1];
        cells[3] = taps[3] - taps[2];
        /* Reject broken taps/implausible data before protection & reporting.
         * These are data validity bounds, not the BMS cutoff thresholds. */
        if (taps[3] < 7.0f || taps[3] > 18.0f) voltageOK = false;
        for (uint8_t i = 0u; i < 4u; ++i) {
            g_bmsAdsCellRawV[i] = cells[i];
            if (cells[i] < 1.5f || cells[i] > 4.5f) voltageOK = false;
        }
        if (!voltageOK) (void)adsFail(0xFFu, 7u);
        else g_bmsAdsValidWindowCount++;
    }

    g_measurementValid = voltageOK && currentOK;
    if (!g_measurementValid) {
        /* Fail-safe: do not allow an ENABLE command while unable to measure. */
        latchProtectionFault();
    }
    if (voltageOK) {
        /* Filter cumulative tap voltage and subtract AFTER filtering.
         * This preserves Cell1+...+Cell4 == filtered tap4 by construction.
         * Raw/unfiltered taps are STILL used for immediate pack safety. */
        if (!s_haveFilter) {
            for (uint8_t i = 0u; i < 4u; ++i) s_filteredTapV[i] = taps[i];
            s_haveFilter = true;
        } else {
            for (uint8_t i = 0u; i < 4u; ++i)
                s_filteredTapV[i] += EMA_ALPHA * (taps[i] - s_filteredTapV[i]);
        }
        Cell1 = s_filteredTapV[0];
        Cell2 = s_filteredTapV[1] - s_filteredTapV[0];
        Cell3 = s_filteredTapV[2] - s_filteredTapV[1];
        Cell4 = s_filteredTapV[3] - s_filteredTapV[2];
        Cell_Tong = s_filteredTapV[3];
        for (uint8_t i = 0u; i < 4u; ++i) {
            float value = (i == 0u) ? Cell1 : (i == 1u) ? Cell2 :
                          (i == 2u) ? Cell3 : Cell4;
            sample.cell_mV[i] = milliUnsigned(value);
        }
        sample.pack_mV = milliUnsigned(Cell_Tong);
        sample.flags |= BMS_FLAG_VOLTAGE_VALID;
        /* Evaluate HARD pack limits with the unfiltered actual sample. */
        if (taps[3] > PACK_OVERVOLT_V || taps[3] < PACK_UNDERVOLT_V)
            latchProtectionFault();
    }
    if (currentOK) {
        s_currentA = currentA;
        sample.current_mA = milliSigned(s_currentA);
        sample.flags |= BMS_FLAG_CURRENT_VALID;
    }
    if (tempOK) {
        /* Round to the nearest centi-degree, including negative values. */
        sample.pack_temp_cC = (int16_t)((tempC >= 0.0f)
            ? (tempC * 100.0f + 0.5f)
            : (tempC * 100.0f - 0.5f));
        sample.flags |= BMS_FLAG_TEMP_VALID;
    }

    if (voltageOK && currentOK) {
        if (!s_socInitialized && now >= SOC_INIT_AFTER_MS) {
            SOC = getPackSocFromVoltage(Cell_Tong);
            s_socInitialized = true;
            s_lastCoulombMs = now;
        } else if (s_socInitialized) {
            const uint32_t elapsedMs = now - s_lastCoulombMs;
            s_lastCoulombMs = now;
            /* Positive ACS712 current means discharge; negative means charge.
             * Validate direction on your hardware before relying on SOC. */
            SOC -= (currentSocA * (float)elapsedMs /
                   (3600000.0f * BATTERY_CAPACITY_AH)) * 100.0f;
            SOC = clampFloat(SOC, 0.0f, 100.0f);
        }
        if (taps[3] > PACK_OVERVOLT_V) SOC = 100.0f;
        if (taps[3] < PACK_UNDERVOLT_V) SOC = 0.0f;
        if (s_socInitialized) {
            sample.soc_centi_pct = (uint16_t)(SOC * 100.0f + 0.5f);
            sample.flags |= BMS_FLAG_SOC_VALID;
        }
    }
    sample.output_enabled = mosfetState;
    if (g_protectionLatched) sample.flags |= BMS_FLAG_FAULT_LATCHED;
    sample.sampled_at_ms = now;
    s_latest = sample;
}

void BMS_App_Init(void)
{
    /* Local protection stays active independently of ESP32/Internet.
     * Start with load OFF and PC13 LED OFF. */
    setLoadOutput(false);

    /* Debounce module initializes all four slots; only PB5 is enabled. */
    BMS_Buttons_Init();
    g_buttonPressCnt = 0u;
    g_buttonRejectedCnt = 0u;
    g_buttonStableState = BMS_Buttons_GetStableState(BMS_BUTTON_1_LOAD);
    if (HAL_ADCEx_Calibration_Start(&hadc1) != HAL_OK) Error_Handler();
    /* Begin 3-second SolGrid splash, without delaying BMS/UART. */
    BMS_LCD_Init(HAL_GetTick());
    if (BMS_Comm_Init(&huart2) != HAL_OK) Error_Handler();
    if (HAL_TIM_Base_Start_IT(&htim2) != HAL_OK) Error_Handler();
}

void BMS_App_Process(void)
{
    static bool started = false;
    static uint32_t lastSensorMs;
    const uint32_t now = HAL_GetTick();
    if (!started) {
        lastSensorMs = now - SENSOR_INTERVAL_MS;
        started = true;
    }
    if ((uint32_t)(now - lastSensorMs) >= SENSOR_INTERVAL_MS) {
        lastSensorMs = now;
        sensorUpdate(now);
    }

    /* Consume button events in main context, never inside TIM2 IRQ.
     * Process AFTER the latest safety measurements, so a newly-detected
     * protection fault cannot be overridden by an ON request. */
    g_buttonStableState = BMS_Buttons_GetStableState(BMS_BUTTON_1_LOAD);
    while (BMS_Buttons_TakePress(BMS_BUTTON_1_LOAD)) {
        handleButtonPress();
    }
    /* Spare button slots 2..4 are intentionally not assigned any action. */
    s_latest.output_enabled = mosfetState;
    if (g_protectionLatched) s_latest.flags |= BMS_FLAG_FAULT_LATCHED;

    BMS_Comm_Service(&s_latest, HAL_GetTick());
    /* Display stays non-blocking for the 3 s splash. */
    BMS_LCD_Process(&s_latest, HAL_GetTick(), true);
}

/* HAL callbacks implemented OUTSIDE generated main.c. Do not duplicate.
 * This callback is a 1 ms event producer, with no I2C/output switching. */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM2)
        BMS_Buttons_Tick1ms();
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    BMS_Comm_OnRxByte(huart);
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    BMS_Comm_OnUartError(huart);
}
